const fieldsAPI = {
  customers: {
    name: "customers",
    arabicName: "زبون",
    fields: ["name", "des", "phone"],
    fieldsUpperCase: ["Name", "Des", "Phone"],
    fieldsTexts: ["إسم", "صفة", "رقم هاتف"],
    updateTitle: "تعديل بيانات الزبون",
    addTitle: "إضافة زبون جديد",
  },
  workers: {
    name: "workers",
    arabicName: "عامل",
    fields: ["name", "phone"],
    fieldsUpperCase: ["Name", "Phone"],
    fieldsTexts: ["إسم", "رقم هاتف"],
    updateTitle: "تعديل بيانات العامل",
    addTitle: "إضافة عامل جديد",
  },
  vegs: {
    name: "vegs",
    arabicName: "صنف",
    fields: ["name"],
    fieldsUpperCase: ["Name"],
    fieldsTexts: ["إسم"],
    updateTitle: "تعديل بيانات الصنف",
    addTitle: "إضافة صنف جديد",
  },
  sellers: {
    name: "sellers",
    arabicName: "بائع",
    fields: ["name", "des", "phone"],
    fieldsUpperCase: ["Name", "Des", "Phone"],
    fieldsTexts: ["إسم", "صفة", "رقم هاتف"],
    updateTitle: "تعديل بيانات البائع",
    addTitle: "إضافة بائع جديد",
  },
  material: {
    name: "material",
    arabicName: "مادة",
    fields: ["name"],
    fieldsUpperCase: ["Name"],
    fieldsTexts: ["إسم"],
    updateTitle: "تعديل بيانات المادة",
    addTitle: "إضافة مادة جديدة",
  },
  currency: {
    name: "currency",
    arabicName: "عملة",
    fields: ["name"],
    fieldsUpperCase: ["Name"],
    fieldsTexts: ["إسم"],
    updateTitle: "تعديل بيانات العملة",
    addTitle: "إضافة عملة جديدة",
  },
  acts: {
    name: "acts",
    arabicName: "عملية",
    fields: ["name"],
    fieldsUpperCase: ["Name"],
    fieldsTexts: ["إسم"],
    updateTitle: "تعديل بيانات العملية",
    addTitle: "إضافة عملية جديدة",
  },
  groups: {
    name: "groups",
    arabicName: "ورشة",
    fields: ["name", "phone"],
    fieldsUpperCase: ["Name", "Phone"],
    fieldsTexts: ["إسم", "رقم هاتف"],
    updateTitle: "تعديل بيانات الورشة",
    addTitle: "إضافة ورشة جديدة",
  },
};
export default fieldsAPI;
